//
//  StyleKit.h
//  PCDemo
//
//  Created by AuthorName on 28.10.14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawNeoSwitchWithAnimation: (CGFloat)animation;

@end
