//
//  StyleKit.m
//  PCDemo
//
//  Created by AuthorName on 28.10.14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawNeoSwitchWithAnimation: (CGFloat)animation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 0.26 green: 0.827 blue: 0.319 alpha: 1];
    UIColor* color3 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color = [UIColor colorWithRed: 0.842 green: 0.842 blue: 0.842 alpha: 1];

    //// Variable Declarations
    CGFloat moveButton = 40 * animation + 3;
    CGFloat rotateButton = 90 * animation;
    UIColor* changeColor = [UIColor colorWithRed: 0.84 - 0.58 * animation green: 0.84 - 0.01 * animation blue: 0.84 - 0.52 * animation alpha: 1];

    //// Switch-Background 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 51, 31);

    UIBezierPath* switchBackground2Path = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(-51, -31, 102, 62) cornerRadius: 31];
    [color setFill];
    [switchBackground2Path fill];

    CGContextRestoreGState(context);


    //// Switch-Background Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 51, 31);
    CGContextScaleCTM(context, animation, animation);

    UIBezierPath* switchBackgroundPath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(-51, -31, 102, 62) cornerRadius: 31];
    [color0 setFill];
    [switchBackgroundPath fill];

    CGContextRestoreGState(context);


    //// Plus
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, (moveButton + 28), 31);
        CGContextRotateCTM(context, -rotateButton * M_PI / 180);



        //// Oval 2 Drawing
        UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-28, -28, 56, 56)];
        [color3 setFill];
        [oval2Path fill];


        //// Rectangle Drawing
        CGContextSaveGState(context);
        CGContextRotateCTM(context, -180 * M_PI / 180);
        CGContextScaleCTM(context, 1, animation);

        UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(-2, -12, 4, 24) cornerRadius: 2];
        [changeColor setFill];
        [rectanglePath fill];

        CGContextRestoreGState(context);


        //// Rectangle 2 Drawing
        CGContextSaveGState(context);
        CGContextRotateCTM(context, -90 * M_PI / 180);

        UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(-2, -12, 4, 24) cornerRadius: 2];
        [changeColor setFill];
        [rectangle2Path fill];

        CGContextRestoreGState(context);



        CGContextRestoreGState(context);
    }
}

@end
